name: Meu primeiro workflow
on: push 

jobs: 

    job1-hello:
        runs-on: ubuntu-latest
        steps:
        - name: Imprimir mensagem
          rum: echo "Olá, Mundo"
    job2-goodbye:
        runs-on: ubunto-latest
        steps:
        - name: Step 1 - Sequencia de instruções
          run: |
            echo "Uma nova instrução"
            ls
        - name: Step 2 - Imprimir mensagem
          run: echo "Até logo!"